const toursData = [
    {
        id: "at-safari",
        location: "Alanya",
        title: "Toros Dağlarında At Safari",
        category: "Macera",
        price: { adult: 300, child: 300, infant: 0, currency: "₺" },
        duration: "09:00 - 13:00",
        days: ["Her Gün"],
        description: "Etkileyici gezimizle Syedra Antik kentini de göreceğiz. Bu antik şehrimizi at sırtında gezeceksiniz ve program hakkında eğitmenlerden, at binişi ile ilgili gerekli teknik bilgileri alacaksınız. Öncelikle parkurda gözetmenler eşliğinde biniciliğe daha fazla hâkim olup, unutulmaz dağ yolculuğuna çıkacaksınız. Yolculuğumuz yaklaşık 3 saat olacaktır.",
        images: ["https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Syedra Antik Kenti", "3 Saat At Binişi", "Profesyonel Eğitim"],
        included: ["Otelden Transferi", "Sigorta", "Profosyenel Eğitmenler", "Tüm Ekipmanlar", "Atlara Biniş"],
        excluded: ["Video ve Fotoğraflar"],
        notes: ["Rahat kıyafet ve spor ayakkabı giyiniz.", "Hamileler için uygun değildir.", "Kilonuzu belirtiniz."]
    },
    {
        id: "antalya-akvaryum",
        location: "Antalya",
        title: "Antalya + Akvaryum Turu",
        category: "Kültür & Aile",
        price: { adult: 300, child: 250, infant: 0, currency: "₺" },
        duration: "08:30 - 18:00",
        days: ["Çarşamba", "Cumartesi"],
        description: "Bu turun avantajı, Alanya ve Antalya güzelliklerinin bir arada olmasıdır. Antalya’da dünyanın en büyük akvaryumlarının birinde, toplam 40 akvaryum ve yaklaşık 20.000 balık ve hatta, batık bir gemi ve denizaltı bulunmaktadır. Su altı etkinliklerinden sonra sizleri öğle yemeği için, restorana götüreceğiz ve sonra gün sonu muhteşem final için sizleri romantik düden şelalesine götüreceğiz.",
        images: [
            "assets/images/tours/antalya-akvaryum/Antalya-Akvaryum-1.png",
            "assets/images/tours/antalya-akvaryum/Antalya-Akvaryum-1_restored_2.png",
            "assets/images/tours/antalya-akvaryum/Antalya-Akvaryum-2_restored_3.png",
            "assets/images/tours/antalya-akvaryum/Antalya-Akvaryum-4_restored_5.png",
            "assets/images/tours/antalya-akvaryum/Antalya-Akvaryum-5_restored_6.png",
            "assets/images/tours/antalya-akvaryum/Antalya-Akvaryum-6_restored_7.png",
            "assets/images/tours/antalya-akvaryum/Antalya-Akvaryum-7_restored_8.png",
            "assets/images/tours/antalya-akvaryum/Antalya-Akvaryum-8_restored_9.png",
            "assets/images/tours/antalya-akvaryum/Antalya-Akvaryum-9_restored_1.png"
        ],
        highlights: ["Dünyanın En Büyük Tünel Akvaryumu", "Düden Şelalesi", "Antalya Şehir Gezisi"],
        included: ["Otel Transferi", "Akvaryuma Giriş Bileti", "Klimalı araçlar ile ulaşım", "Öğle Yemeği"],
        excluded: ["İçecekler", "XD Sinema", "Kar Dünyası ve Botanik Bahçe (10-15 Euro)"],
        notes: ["01 Haziran - 30 Eylül arası yapılır", "Kimlik bulundurunuz", "Akvaryumda flaş yasak", "Çocuk (3-6 yaş): 125 ₺"]
    },
    {
        id: "rafting-turu",
        location: "Manavgat",
        title: "Rafting Turu",
        category: "Macera",
        price: { adult: 150, child: 60, infant: 0, currency: "₺" },
        duration: "09:00 - 18:00",
        days: ["Her Gün"],
        description: "Heyecan verici Rafting etkinliğimiz, köprülü kanyonda gerçekleştirilir. Kanyon, Milli Park ile Toros Dağları arasında yer almaktadır. Rafting yapılacak bölgeye giderken, Beşkonak Köyünden geçiş yapılacaktır. Köyün özelliği evlerinin taştan olmasıdır.",
        images: ["https://images.unsplash.com/photo-1530866495561-507c9faab2ed?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Köprülü Kanyon", "14 km Parkur", "Öğle Yemeği Dahil"],
        included: ["Otel Transferi", "Ekipman ve Eğitmen Ücreti", "Klimalı Araçlarla Ulaşım", "Öğle Yemeği"],
        excluded: ["İçecekler", "Fotoğraf ve Videolar (Yaklaşık 20 €)", "Rafting Kıyafet Kirası"],
        notes: [
            "Turumuz 01 Nisan - 31 Ekim tarihleri arasında gerçekleşmektedir.",
            "Yanınızda mayo, havlu, Rafting için ayakkabı, güneş kremi ve biraz nakit bulundurunuz.",
            "Rafting 5 yaşından büyük çocuklar için uygundur.",
            "Rafting bölgesinde kıyafet kabinleri mevcuttur; kişisel eşyalar otobüste bırakılabilir.",
            "Görevliler size uygun can yeleği ve kask temin edecektir.",
            "Katılımcılar 10 kişilik gruplara ayrılır ve her botta profesyonel bir eğitmen bulunur.",
            "Su korkusu olan çocuklar botun ortasında, küreksiz ve güvenli bir şekilde oturabilir.",
            "Gözlük kullanan misafirlerimiz gözlüklerini kasklarının içinde sabitlemelidir.",
            "Rafting için özel ayakkabılar giyilmelidir (tesisten temin edilebilir).",
            "Suya dayanıklı olmayan kamera/telefonların bota alınması önerilmez.",
            "Hamileler, sırt problemi olanlar ve astım hastaları için uygun değildir.",
            "Rehberlik hizmeti çoklu dilde (Türkçe, İngilizce, Rusça, Almanca) verilmektedir."
        ]
    },
    {
        id: "rafting-extra",
        location: "Manavgat",
        title: "Rafting Extra Turu",
        category: "Macera",
        price: { adult: 230, child: 60, infant: 0, currency: "₺" },
        duration: "09:00 - 19:00",
        days: ["Her Gün"],
        description: "Eğer ekstrem sporları seviyorsanız, bu tur tam size göre. 3 ü 1 arada. Rafting, kano ve zipline. Bütün aktiviteler Toros Dağları Köprülü Kanyonunda gerçekleştirilir. Bu hayatınız boyunca unutulmayacak, yaklaşık 10km'lik bir tecrübe olacaktır.",
        images: ["https://images.unsplash.com/photo-1544085311-11a028465b03?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Rafting + Kano + Zipline", "3'ü 1 Arada", "10km Parkur"],
        included: ["Otel Transferi", "Ekipmanlar (Kask, Kürek, Can Yeleği)", "Eğitmen Ücreti", "Klimalı araçlar ile ulaşım", "Öğle Yemeği", "Sigorta"],
        excluded: ["İçecekler", "Fotoğraf ve Videolar (Yaklaşık 20 €)", "Özel Kıyafet Kirası"],
        notes: [
            "Rafting + Kano: 15 Nisan – 31 Ekim. Her gün.",
            "Rafting + Kano + Zipline: 15 Nisan - 31 Ekim, Salı, Perşembe, Cumartesi.",
            "Zipline için ağırlık limitleri 30kg-110kg arasıdır.",
            "Çocuklar ebeveynlerinin sorumluluğunda katılabilirler.",
            "Tur küçük gruplar için müsaittir.",
            "Rafting 5 yaşından büyük çocuklar için uygundur.",
            "Yanınızda mayo, havlu, Rafting için ayakkabı, güneş kremi ve biraz nakit bulundurunuz.",
            "Hamileler, sırt problemi olanlar ve astım hastaları için uygun değildir.",
            "Suya dayanıklı olmayan kamera/telefonların bota alınması önerilmez.",
            "Rafting + Zipline Çocuk (7-12) ücreti: 180 ₺, Yetişkin: 350 ₺ (Opsiyonel)"
        ]
    },
    {
        id: "alanya-tekne-turu",
        location: "Alanya",
        title: "Alanya Tekne Turu (Mavi Tur)",
        category: "Tekne & Deniz",
        price: { adult: 110, child: 60, infant: 0, currency: "₺" },
        duration: "09:30 - 15:00",
        days: ["Her Gün"],
        description: "Eğer yolunuz bir gün Alanya’dan geçerse, bir değişiklik arıyorsanız, sizi (tekne bot turu) Mavi Tur’a davet ediyoruz. Saat 10:00 da yelken açtığımız yolculuğumuzda Alanya’nın sembolü olan Kızıl Kule’yi, surları ve görkemli Alanya Kalesini göreceksiniz. Eğer şanslıysanız yunusları ve caretta carettaları bile görebilirsiniz. Bu etkinlik sizin için önemli bir anı olacaktır.",
        images: [
            "assets/images/tours/alanya-tekne-turu/Alanya Tekne Turu 1_restored_1.png",
            "assets/images/tours/alanya-tekne-turu/Alanya Tekne Turu 2_restored_2.png",
            "assets/images/tours/alanya-tekne-turu/Alanya Tekne Turu 4_restored_3.png",
            "assets/images/tours/alanya-tekne-turu/Alanya Tekne Turu 5_restored_4.png",
            "assets/images/tours/alanya-tekne-turu/Alanya Tekne Turu 6_restored_5.png",
            "assets/images/tours/alanya-tekne-turu/Alanya Tekne Turu 7_restored_6.png",
            "assets/images/tours/alanya-tekne-turu/Alanya Tekne Turu 9_restored_7.png"
        ],
        highlights: ["Alanya Kalesi & Kızıl Kule", "Yunuslar & Caretta Carettalar", "Köpük Partisi"],
        included: ["Otel Transferi", "Öğle Yemeği", "Limitsiz Soğuk Alkolsüz İçecekler", "Animasyon", "Köpük Partisi"],
        excluded: ["Sıcak İçecekler", "Alkollü İçecekler", "Dondurma"],
        notes: [
            "15 Nisan- 30 Ekim tarihleri arasında her gün düzenlenmektedir.",
            "Yanınızda mayo, havlu, güneş kremi, şapka ve biraz nakit para bulundurunuz.",
            "Teknede şezlong yerine güneşlenme matları mevcuttur.",
            "Teknede tuvalet ve soyunma kabinleri bulunmaktadır.",
            "Rehberlik dilleri: Türkçe, İngilizce, Almanca, Rusça"
        ]
    },
    {
        id: "mini-alanya-jeep",
        location: "Alanya",
        title: "Mini Alanya Jeep Şehir Turu",
        category: "Gezi & Kültür",
        price: { adult: 90, child: 60, infant: 0, currency: "₺" },
        duration: "16:30 - 19:30",
        days: ["Her Gün"],
        description: "Birkaç saatliğine güzel bir fırsat istiyorsanız bu turu kaçırmamalısınız. Alanya'nın Selçuklu Türklerinden kalma kuvvetli kale duvarları, tarihi cami, Damlataş Mağarası bu turun görülmesi gerekenler arasındadır. Mağara içi yıl boyunca 18-19°C olup nem oranı %80 dolaylarındadır.",
        images: ["https://images.unsplash.com/photo-1621849400072-f554417f7051?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Alanya Kalesi", "Damlataş Mağarası", "Seyir Terası"],
        included: ["Otel Transferi", "Rehber", "4x4 Jeepler ile Tur"],
        excluded: ["Mağara giriş bileti (10 TL)"],
        notes: [
            "15 Nisan- 31 Ekim tarihleri arasında her gün düzenlenmektedir.",
            "Yanınızda biraz para, kamera getirebilirsiniz.",
            "Tur çoklu yabancı dil rehberleri tarafından icra edilebilir. (Türkçe, İngilizce, Lehçe)",
            "Bayan misafirlerimiz, Cami ziyaretinde başörtüsü kullanmak zorundadır.",
            "Gezi sadece Mahmutlar, Kargacık, Kestel, Tosmur, Obagöl ve Alanya merkezden katılıma uygundur."
        ]
    },
    {
        id: "gece-safarisi",
        location: "Alanya",
        title: "Gece Safarisi",
        category: "Safari",
        price: { adult: 200, child: 120, infant: 0, currency: "₺" },
        duration: "18:30 - 00:30",
        days: ["Pazartesi", "Çarşamba", "Cuma"],
        description: "Öncelikle Kale tepesinde gün batımına gideceğiz. Bu muhteşem panoramik manzarada, eşsiz fotoğraf çekerken bir kadeh şarap ve şampanya ile eğlencemize başlıyoruz. Korkusuz sürücülerimiz sizleri daha cesur yollardan, yemek yiyeceğimiz müthiş manzaralı restoranımıza götürecek. Yemek sonrası biraz yüksek sürati de işin içine katıp, adrenalin katsayısını da arttırıyoruz.",
        images: ["https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Gün Batımı", "Panoramik Manzara", "Adrenalin", "Akşam Yemeği"],
        included: ["Otel Transferi", "Akşam Yemeği"],
        excluded: ["İçecekler"],
        notes: [
            "Yanınızda para, kamera ve rahat edebileceğiniz ayakkabılar getirmelisiniz.",
            "Tur çoklu yabancı dil rehberleri tarafından icra edilebilir. (Türkçe, İngilizce)",
            "Eğer oteliniz Okurcalarda ise fiyatımıza +5€ etkisi vardır.",
            "7 yaş altı çocuklar için uygun değildir.",
            "Hamile ve sırt problemi olanlar için önerilmez."
        ]
    },
    {
        id: "yamac-parasutu",
        location: "Alanya",
        title: "Yamaç Paraşütü",
        category: "Adrenalin",
        price: { adult: 500, child: 500, infant: 0, currency: "₺" },
        duration: "2 Saat (Uçuş Süresi 30 dk)",
        days: ["Her Gün"],
        description: "Gökyüzünde kuşlar gibi süzülmenin inanılmaz tecrübesi... Uzman eğitmenlerimizle şahane bir uçuş. Alanya ve Cleopatra Plajı üzerine iniş fırsatı olacak. Sizleri Alanya'nın en yüksek yerlerinden biri olan, yaklaşık 700m'lik bir irtifada olan paraşüt kalkış alanına götüreceğiz. Hazırlıklarınız bittikten sonra, birkaç adımlık koşu sonra ayaklarınız yerden kesilecek ve unutulmaz bir tecrübe başlamış olacak. Kuş bakışı tüm Alanya'yı, sahilleri ve denizi göreceksiniz.",
        images: ["https://images.unsplash.com/photo-1474302770737-173ee21bab63?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["700m Yükseklik", "Cleopatra Plajı İniş", "Profesyonel Pilot"],
        included: ["Otel Transferi", "Ekipmanlar", "Sigorta", "Eğitmen"],
        excluded: ["Uçuş Fotoğraf ve Videoları"],
        notes: [
            "15 Nisan - 31 Ekim tarihleri arasında her gün.",
            "Rahat edeceğiniz bir ayakkabı giymeyi unutmayın.",
            "Uçuş planınız hava şartlarına göre değişebilir.",
            "Rüzgâr durumu ve kilonuz uçuş süresini etkileyebilir.",
            "Katılımcılar 20kg ile 110kg arası olmalıdır.",
            "Yükseklik korkusu ve astımı olanlar için uygun değildir.",
            "Eşlik Eden Kişi Ücreti: 125 ₺"
        ]
    },
    {
        id: "yunus-gosterisi",
        location: "Alanya",
        title: "Yunus Gösterisi (SHOW)",
        category: "Eğlence & Aktivite",
        price: { adult: 240, child: 180, infant: 0, currency: "₺" },
        duration: "09:00-12:00 veya 14:00-17:00",
        days: ["Her Gün"],
        description: "Yunusları fokların ve denizaslanlarının 1 saatlik unutulmaz gösterisi. Yunusların, özellikle hiperaktif çocuklar üzerinde etkisi çok büyüktür. Thalassotherapy etkisiyle çocuklara sakinlik kazandırırlar. Yunus ile yüzme seçeneğinde, sadece yüzme değil, ayrıca yunusu besleme, yunus ile dans etme ve hatta öpmekte paket içeriğindedir.",
        images: ["https://images.unsplash.com/photo-1568430462989-44163eb1752f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Yunus Gösterisi", "Fok Gösterisi", "Deniz Aslanları"],
        included: ["Otel Transferi", "Giriş Bileti", "Rehber"],
        excluded: ["Yunus ile fotoğraf (160 TL civarı)", "Yunus ile yüzmek (900 TL civarı)"],
        notes: [
            "1 Mayıs - 30 Eylül arası her gün.",
            "Yanınızda kamera ve para getiriniz.",
            "Gösteri süresince flaşsız fotoğraf çekebilirsiniz.",
            "Yunusla yüzme için rezervasyon gereklidir.",
            "120cm'den büyük çocuklar yunus ile yüzebilir.",
            "Hamileler ve engelli misafirler için yüzme uygun değildir.",
            "Çocuk indirimi için kimlik gereklidir."
        ]
    },
    {
        id: "quad-safari",
        location: "Alanya",
        title: "Quad Safari / Buggy Cross",
        category: "Macera",
        price: { adult: 200, child: 200, infant: 0, currency: "₺" },
        duration: "3 Saat (09:00-12:00 veya 14:00-17:00)",
        days: ["Her Gün"],
        description: "ATV veya Buggy araçlarıyla çamur, toz ve su parkurlarında eğlence dolu bir macera sizi bekliyor. Toros dağlarının eteklerinde, doğayla iç içe, adrenalin dolu bir sürüş deneyimi.",
        images: ["https://images.unsplash.com/photo-1551817958-c5b56d360061?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Off-Road Macera", "Doğa Parkuru", "Rehberli Tur"],
        included: ["Otel Transferi", "Kask", "Araç (ATV/Buggy)", "Sigorta"],
        excluded: ["İçecekler", "Fotoğraf / Video"],
        notes: [
            "1 Nisan - 31 Ekim tarihleri arasında her gün.",
            "Yanınızda kirlenebilecek rahat kıyafetler, ayakkabılar, güneş gözlüğü ve bandana getiriniz.",
            "13 yaşından küçükler sadece yolcu olarak katılabilir.",
            "Herkes yetişkin ücreti üzerinden ücretlendirilir.",
            "Yaz aylarında tozdan korunmak için yüz maskesi/bandana önerilir.",
            "Sürüş öncesi test yapılır; zorlananlar eğitmen eşliğinde devam eder.",
            "Çift Quad: 375 ₺, Tek Buggy: 300 ₺, Çift Buggy: 400 ₺ (Ekstra)"
        ]
    },
    {
        id: "dalis",
        location: "Alanya",
        title: "Dalış / Diving",
        category: "Su Sporları",
        price: { adult: 300, child: 85, infant: 0, currency: "₺" },
        duration: "09:00-15:00",
        days: ["Her Gün"],
        description: "Bu etkinlik yeniliklere açık olanlar içindir. İlk etapta 5m, ikinci etapta 8m'ye kadar dalma fırsatı. İki etap arasında öğle yemeği, Akdeniz'in derinlikleri keşfedilmeyi bekliyor! 13 yaşından büyük yüzmeyi bilen herkes dalış yapabilir.",
        images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["2 Dalış Etabı", "5m ve 8m Derinlik", "Sertifikalı Eğitmenler"],
        included: ["Otel Transferi", "Öğle Yemeği", "Profesyonel Dalış Ekipmanları", "2 Dalış Etabı", "Eğitmen"],
        excluded: ["İçecekler", "Fotoğraf / Video"],
        notes: [
            "Yanınızda mayo, havlu, para, kamera, güneş gözlüğü ve güneş kremi getiriniz.",
            "13 yaşından büyük ve yüzme bilen herkes dalış yapabilir.",
            "Her dalış yaklaşık 30 dk sürer.",
            "Sertifikalı dalgıçlar, sertifikalarının izin verdiği derinliklere dalabilirler.",
            "Eşlik Eden Yetişkin: 200 ₺ (Dalış yapmayacaklar için)",
            "Eşlik Eden Çocuk (7-12): 85 ₺",
            "0-6 Yaş Bebek: Ücretsiz"
        ]
    },
    {
        id: "aquapark",
        location: "Alanya",
        title: "Aquapark",
        category: "Eğlence & Aktivite",
        price: { adult: 250, child: 200, infant: 0, currency: "₺" },
        duration: "09:00-17:00",
        days: ["Her Gün"],
        description: "Otel havuzu sizin için küçükse, tüm ailenizi Eftelya Adasına muhteşem bir gün geçirmeye davet ediyoruz. Yetişkinler ve çocuklar için çeşitli havuzlar kaydıraklar ve animasyonların yanı sıra, su parkının plajda yer almasının avantajıyla deniz ve havuz keyfine varabilirsiniz.",
        images: ["https://images.unsplash.com/photo-1582653291997-079a1c04e5a1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Eftelya Adası", "Su Parkı & Plaj", "Her Şey Dahil"],
        included: ["Otel Transferi", "Şezlong", "Limitsiz Yerel Alkollü ve Alkolsüz İçecekler", "Yemek (Kebap, Pizza, Burger, Dondurma)"],
        excluded: ["Sahilde Su Sporları"],
        notes: [
            "1 Mayıs - 31 Ekim arası her gün.",
            "Yanınızda mayo, havlu, para, kamera, güneş gözlüğü, şapka ve güneş kremi getiriniz.",
            "Misafirlerimiz bireysel kilitli dolaplara sahip olacaktır.",
            "Yemekler ve içecekler, su parkının bütün restoranlarından temin edilebilir.",
            "Çocuklar her zaman ebeveynlerinin yanında olmalıdır."
        ]
    },
    {
        id: "green-kanyon",
        location: "Manavgat",
        title: "Green Kanyon (Yeşil Vadi)",
        category: "Doğa & Keşif",
        price: { adult: 300, child: 200, infant: 0, currency: "₺" },
        duration: "08:30-17:00",
        days: ["Pazartesi", "Çarşamba", "Cuma"],
        description: "Bu tur, Manavgat Nehrinin alt kesimlerinde başlar ve büyük baraja doğru ilerler. Baraj 185mlik boyutuyla Türkiye'nin en yükseklerinden biridir. Barajdan, muhteşem yeşil vadiyi gözlemleme fırsatı bulabilirsiniz.",
        images: ["https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Manavgat Nehri", "Oymapınar Barajı", "Yeşil Vadi Manzarası", "Yüzme Molası"],
        included: ["Otel Transferi", "Alkolsüz İçecek", "Öğle Yemeği"],
        excluded: ["Alkollü İçecek"],
        notes: [
            "1 MAYIS - 30 EYLÜL Pazartesi, Çarşamba, Cuma.",
            "Yanınızda mayo, havlu, para, kamera, güneş gözlüğü, şapka, güneş kremi getiriniz.",
            "Teknede yalnızca oturmak için koltuklar bulunmaktadır. Güneşlenmeye elverişli değildir.",
            "Tur çoklu yabancı dil rehberleri tarafından icra edilebilir."
        ]
    },
    {
        id: "manavgat-tekne-turu",
        location: "Manavgat",
        title: "Manavgat Tekne Turu",
        category: "Tekne & Deniz",
        price: { adult: 200, child: 100, infant: 0, currency: "₺" },
        duration: "08:30-17:00",
        days: ["Pazartesi", "Perşembe"],
        description: "Manavgat Side’nin yanında büyük bir şehirdir. Şehir, Akdeniz'in en büyük Camisine ev sahipliği yapmaktadır. Cami sonrası Manavgat şelalesine doğru yola çıkıyoruz. Manavgat'ın, denizle buluştuğu noktadan çıkanlar için, leziz barbekü sizi beklemektedir. Gün sonunda Akdeniz'in en büyük turistik pazarından alışveriş yaparak bu güzel güne nokta koyuyoruz.",
        images: ["https://images.unsplash.com/photo-1596395819057-d37b251d1372?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Manavgat Şelalesi", "Akdeniz'in En Büyük Camisi", "Turistik Pazar", "Nehir & Deniz Birleşimi"],
        included: ["Otel Transferi", "Teknede Öğlen Yemeği"],
        excluded: ["İçecekler", "Şelalelere Giriş Bileti"],
        notes: [
            "15 Nisan - 15 Ekim Pazartesi, Perşembe.",
            "Yanınızda mayo, havlu, para, kamera, güneş gözlüğü, şapka ve güneş kremi getiriniz.",
            "Cami girişinde başörtüsü ve kısa şortlu misafirlerimiz için uzun etek giyilmesi gerekmektedir.",
            "Ayakkabıların çıkarılması zorunludur.",
            "Bebek indirimi yalnızca bebek için koltuk kullanmıyorsa uygulanabilir."
        ]
    },
    {
        id: "deniz-yoluyla-alanya",
        location: "Alanya",
        title: "Deniz Yoluyla Alanya",
        category: "Tekne & Deniz",
        price: { adult: 200, child: 90, infant: 0, currency: "₺" },
        duration: "08:30-17:00",
        days: ["Salı", "Cuma", "Pazar"],
        description: "Eğer otelinizden uzak havuz veya sahilde bir gün geçirmek isterseniz bu tur tam size göredir. Eğer şanslıysanız tur sırasında, yunuslar ve caretta carettalarla karşılaşabilir ve bu Akdeniz güzelliğini tecrübe edebilirsiniz. Alanya’nın 20 km açıklarına kadar sürecek tekne gezisi açık denizde demir atacaktır. Dönüş yolunda öğle yemeği, animasyonlar ve müziğin keyfini çıkarabilirsiniz.",
        images: ["https://images.unsplash.com/photo-1502085671122-2d218cd434e6?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Yunus ve Caretta Caretta Gözlemi", "Açık Deniz Yüzme Molası", "Animasyon ve Müzik", "Öğle Yemeği"],
        included: ["Otel Transferi", "Öğlen Yemeği"],
        excluded: ["İçecekler", "Dondurma"],
        notes: [
            "1 Mayıs - 15 Ekim Salı, Cuma, Pazar.",
            "Yanınızda mayo, havlu, para, kamera, güneş gözlüğü, şapka, güneş kremi getiriniz.",
            "Teknede şezlonglar haricinde güneşlenme matları bulunmaktadır.",
            "Tur ve fiyatlar Avşallar, İncekum, Karaburun, Okurcalar, Kızılot, Cenger hotellerinden geçerlidir.",
            "Teknede kıyafet kabinleri ve tuvaletler mevcuttur."
        ]
    },
    {
        id: "jeep-safari",
        location: "Alanya",
        title: "Jeep Safari",
        category: "Safari",
        price: { adult: 130, child: 75, infant: 0, currency: "₺" },
        duration: "09:00 - 16:00",
        days: ["Her Gün"],
        description: "Toros dağlarının eteklerinde, doğa ile iç içe, eğlenceli ve macera dolu bir Jeep Safari turu. Nehir kenarında öğle yemeği molası ile günün yorgunluğunu atabilirsiniz.",
        images: ["https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Toros Dağları", "Off-Road Macera", "Nehir Kenarı Yemek"],
        included: ["Otel Transferi", "Jeep Yolculuğu", "Nehir Kenarında Öğlen Yemeği"],
        excluded: ["İçecekler", "DVD ve Fotoğraflar"],
        notes: [
            "1 Nisan - 31 Ekim Her gün.",
            "Yanınızda mayo, havlu, rahat ayakkabılar, kamera, güneş gözlüğü, güneş kremi ve şapka getiriniz.",
            "Cami girişinde başörtüsü ve uzun etek giyilmesi gerekmektedir (temin edilebilir).",
            "Cami girişinde ayakkabılarınızı çıkarmanız gerekmektedir.",
            "Hamileler ve sırt problemi olanlar için önerilmez."
        ]
    },
    {
        id: "sapadere-kanyonu",
        location: "Alanya",
        title: "Jeep Sapadere",
        category: "Doğa & Keşif",
        price: { adult: 180, child: 100, infant: 0, currency: "₺" },
        duration: "09:00 - 17:00",
        days: ["Her Gün"],
        description: "Jeeple, Toros Dağlarında Türkiye'nin, en güzel vadilerinde yolculuk keyfi. Ayrıca gezi sırasında, bir köy evine misafir olacağız.",
        images: ["https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80"],
        highlights: ["Toros Dağları", "Sapadere Kanyonu", "Köy Evi Ziyareti"],
        included: ["Otel Transferi", "Öğle Yemeği", "Jeep Yolculuğu", "Vadi Giriş Bileti"],
        excluded: ["İçecekler", "Mağara Giriş Bedeli (3 €)"],
        notes: [
            "1 Nisan - 31 Ekim Hergün",
            "Yanınızda mayo, havlu, rahat ayakkabılar, kamera, güneş gözlüğü ve kremi, şapka getiriniz.",
            "Bebek yemeği dâhil değildir.",
            "Tur, çoklu yabancı dil rehberleri tarafından icra edilebilir.",
            "Hamileler ve sırt problemi olanlar için önerilmez."
        ]
    }
];
